[0.000000] (-) TimerEvent: {}
[0.000805] (my_first_delta) JobQueued: {'identifier': 'my_first_delta', 'dependencies': OrderedDict()}
[0.000873] (my_first_delta) JobStarted: {'identifier': 'my_first_delta'}
[0.099755] (-) TimerEvent: {}
[0.199994] (-) TimerEvent: {}
[0.300254] (-) TimerEvent: {}
[0.400508] (-) TimerEvent: {}
[0.450803] (my_first_delta) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/sequential.py", line 48, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.10/selectors.py", line 469, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 90, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 188, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'-W\', \'ignore:setup.py install is deprecated\', \'setup.py\', \'--help-commands\'] to pass: Traceback (most recent call last):\n  File "/home/sanmaster/onshape-to-robot-tutorial/delta_robot_min_ws/src/my_first_delta/setup.py", line 1, in <module>\n    from setuptools import find_packages, setup\n  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 16, in <module>\n    import setuptools.version\n  File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>\n    import pkg_resources\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>\n    def _initialize_master_working_set():\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside\n    f(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in _build_master\n    ws = cls()\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 557, in __init__\n    self.add_entry(entry)\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 614, in add_entry\n    self.add(dist, entry, False)\n  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 701, in add\n    if dist.key not in keys2:\nKeyboardInterrupt\n\n'}
[0.451835] (my_first_delta) JobEnded: {'identifier': 'my_first_delta', 'rc': 'SIGINT'}
[0.452133] (-) EventReactorShutdown: {}
